language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
script:
  - 'npm run lint'
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: 'aeweidne@us.ibm.com'
  on:
      tags: true
